/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedIconsRouteImport } from './routes/_authenticated/icons'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAudioRouteImport } from './routes/_authenticated/audio'
import { Route as AuthenticatedPlaylistsIndexRouteImport } from './routes/_authenticated/playlists.index'
import { Route as ApiYotoCallbackRouteImport } from './routes/api/yoto/callback'
import { Route as ApiYotoAuthorizeRouteImport } from './routes/api/yoto/authorize'
import { Route as ApiYotoAudioRouteImport } from './routes/api/yoto/audio'
import { Route as AuthenticatedPlaylistsPlaylistIdRouteImport } from './routes/_authenticated/playlists.$playlistId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIconsRoute = AuthenticatedIconsRouteImport.update({
  id: '/icons',
  path: '/icons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAudioRoute = AuthenticatedAudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaylistsIndexRoute =
  AuthenticatedPlaylistsIndexRouteImport.update({
    id: '/playlists/',
    path: '/playlists/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiYotoCallbackRoute = ApiYotoCallbackRouteImport.update({
  id: '/api/yoto/callback',
  path: '/api/yoto/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYotoAuthorizeRoute = ApiYotoAuthorizeRouteImport.update({
  id: '/api/yoto/authorize',
  path: '/api/yoto/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYotoAudioRoute = ApiYotoAudioRouteImport.update({
  id: '/api/yoto/audio',
  path: '/api/yoto/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlaylistsPlaylistIdRoute =
  AuthenticatedPlaylistsPlaylistIdRouteImport.update({
    id: '/playlists/$playlistId',
    path: '/playlists/$playlistId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audio': typeof AuthenticatedAudioRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/icons': typeof AuthenticatedIconsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/playlists/$playlistId': typeof AuthenticatedPlaylistsPlaylistIdRoute
  '/api/yoto/audio': typeof ApiYotoAudioRoute
  '/api/yoto/authorize': typeof ApiYotoAuthorizeRoute
  '/api/yoto/callback': typeof ApiYotoCallbackRoute
  '/playlists/': typeof AuthenticatedPlaylistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audio': typeof AuthenticatedAudioRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/icons': typeof AuthenticatedIconsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/playlists/$playlistId': typeof AuthenticatedPlaylistsPlaylistIdRoute
  '/api/yoto/audio': typeof ApiYotoAudioRoute
  '/api/yoto/authorize': typeof ApiYotoAuthorizeRoute
  '/api/yoto/callback': typeof ApiYotoCallbackRoute
  '/playlists': typeof AuthenticatedPlaylistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/audio': typeof AuthenticatedAudioRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/icons': typeof AuthenticatedIconsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRoute
  '/_authenticated/playlists/$playlistId': typeof AuthenticatedPlaylistsPlaylistIdRoute
  '/api/yoto/audio': typeof ApiYotoAudioRoute
  '/api/yoto/authorize': typeof ApiYotoAuthorizeRoute
  '/api/yoto/callback': typeof ApiYotoCallbackRoute
  '/_authenticated/playlists/': typeof AuthenticatedPlaylistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/audio'
    | '/dashboard'
    | '/icons'
    | '/settings'
    | '/tools'
    | '/playlists/$playlistId'
    | '/api/yoto/audio'
    | '/api/yoto/authorize'
    | '/api/yoto/callback'
    | '/playlists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/audio'
    | '/dashboard'
    | '/icons'
    | '/settings'
    | '/tools'
    | '/playlists/$playlistId'
    | '/api/yoto/audio'
    | '/api/yoto/authorize'
    | '/api/yoto/callback'
    | '/playlists'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/audio'
    | '/_authenticated/dashboard'
    | '/_authenticated/icons'
    | '/_authenticated/settings'
    | '/_authenticated/tools'
    | '/_authenticated/playlists/$playlistId'
    | '/api/yoto/audio'
    | '/api/yoto/authorize'
    | '/api/yoto/callback'
    | '/_authenticated/playlists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiYotoAudioRoute: typeof ApiYotoAudioRoute
  ApiYotoAuthorizeRoute: typeof ApiYotoAuthorizeRoute
  ApiYotoCallbackRoute: typeof ApiYotoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/icons': {
      id: '/_authenticated/icons'
      path: '/icons'
      fullPath: '/icons'
      preLoaderRoute: typeof AuthenticatedIconsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audio': {
      id: '/_authenticated/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AuthenticatedAudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playlists/': {
      id: '/_authenticated/playlists/'
      path: '/playlists'
      fullPath: '/playlists/'
      preLoaderRoute: typeof AuthenticatedPlaylistsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/yoto/callback': {
      id: '/api/yoto/callback'
      path: '/api/yoto/callback'
      fullPath: '/api/yoto/callback'
      preLoaderRoute: typeof ApiYotoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/yoto/authorize': {
      id: '/api/yoto/authorize'
      path: '/api/yoto/authorize'
      fullPath: '/api/yoto/authorize'
      preLoaderRoute: typeof ApiYotoAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/yoto/audio': {
      id: '/api/yoto/audio'
      path: '/api/yoto/audio'
      fullPath: '/api/yoto/audio'
      preLoaderRoute: typeof ApiYotoAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/playlists/$playlistId': {
      id: '/_authenticated/playlists/$playlistId'
      path: '/playlists/$playlistId'
      fullPath: '/playlists/$playlistId'
      preLoaderRoute: typeof AuthenticatedPlaylistsPlaylistIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAudioRoute: typeof AuthenticatedAudioRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIconsRoute: typeof AuthenticatedIconsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRoute
  AuthenticatedPlaylistsPlaylistIdRoute: typeof AuthenticatedPlaylistsPlaylistIdRoute
  AuthenticatedPlaylistsIndexRoute: typeof AuthenticatedPlaylistsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAudioRoute: AuthenticatedAudioRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIconsRoute: AuthenticatedIconsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRoute,
  AuthenticatedPlaylistsPlaylistIdRoute: AuthenticatedPlaylistsPlaylistIdRoute,
  AuthenticatedPlaylistsIndexRoute: AuthenticatedPlaylistsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiYotoAudioRoute: ApiYotoAudioRoute,
  ApiYotoAuthorizeRoute: ApiYotoAuthorizeRoute,
  ApiYotoCallbackRoute: ApiYotoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
